name: Update Dependencies

on:
  schedule:
    - cron: '0 12 * * 6' # Every Saturday at 12:00 PM UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Push branches, merge PRs, delete branches
      pull-requests: write # Create and merge PRs
      actions: write # Run check workflows
    steps:
      - name: Run dependency update
        uses: cloud-copilot/action-update-dependencies@fe48d42724df9c4ed34abf9c0cc97a8da42917f4
        with:
          check-workflow: pr-checks.yml
          post-merge-workflow: release.yml
